Package : packages/Package.php
Routing : routing/Routing.php
Spyc : spyc-master/Spyc.php
DrakkarDController : controller/DrakkarDController.php
DrakkarDException : drakkarDException/DrakkarDException.php